services:
  postgres:
    image: postgres:latest
    container_name: todo-db-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      # Volumen para persistir los datos
      - postgres_data:/var/lib/postgresql/data
      # - ./scripts/init-db:/docker-entrypoint-initdb.d/

volumes:
  postgres_data: